
title = "Hello World!"
description = "Luci config hello world example."

[bash]
format = "zig fmt ."
test = "zig build test"
build = "zig build"
run-examples = """
zig build example:hello-world &&
zig build example:moving-box &&
zig build example:moving-scene &&
zig build example:explosion &&
zig build example:svg &&
zig build example:geometric-shapes &&
zig build example:gui &&
zig build example:falling-box
"""

[bash.example]
hello-world = "zig build example:hello-world"
moving-box = "zig build example:moving-box"
moving-scene = "zig build example:moving-scene"
explosion = "zig build example:explosion"
svg = "zig build example:svg"
geometric-shapes = "zig build example:geometric-shapes"
gui = "zig build example:gui"
falling-box = "zig build example:falling-box"

[zshell]
format = "zig fmt ."
test = "zig build test"
build = "zig build"
run-examples = """
zig build example:hello-world &&
zig build example:moving-box &&
zig build example:moving-scene &&
zig build example:explosion &&
zig build example:svg &&
zig build example:geometric-shapes &&
zig build example:gui &&
zig build example:falling-box
"""

[zshell.example]
hello-world = "zig build example:hello-world"
moving-box = "zig build example:moving-box"
moving-scene = "zig build example:moving-scene"
explosion = "zig build example:explosion"
svg = "zig build example:svg"
geometric-shapes = "zig build example:geometric-shapes"
gui = "zig build example:gui"
falling-box = "zig build example:falling-box"

[bat]
format = "zig fmt ."
test = "zig build test"
build = "zig build"
run-examples = """
zig build example:hello-world &&
zig build example:moving-box &&
zig build example:moving-scene &&
zig build example:explosion &&
zig build example:svg &&
zig build example:geometric-shapes &&
zig build example:gui &&
zig build example:falling-box
"""

[bat.example]
hello-world = "zig build example:hello-world"
moving-box = "zig build example:moving-box"
moving-scene = "zig build example:moving-scene"
explosion = "zig build example:explosion"
svg = "zig build example:svg"
geometric-shapes = "zig build example:geometric-shapes"
gui = "zig build example:gui"
falling-box = "zig build example:falling-box"
